version: "3.2"

services:
  app_1:
    image: cp-kafka-test:6.2.0
    build:
      context: ./kafka
      dockerfile: Dockerfile
    hostname: kafka_1
    links:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_1:9092,INTERNAL_SECURE://kafka_1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, INTERNAL_SECURE:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SECURE
      KAFKA_OPTS: " -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server.jaas "
      ZOOKEEPER_SET_ACL: "false"
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.auth.SimpleAclAuthorizer"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: "User:admin"
    ports:
      - 9092
      - 9094
  app_2:
    image: cp-kafka-test:6.2.0
    image: cp-kafka-test:6.2.0
    build:
      context: ./kafka
      dockerfile: Dockerfile
    hostname: kafka_2
    links:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_2:9092,INTERNAL_SECURE://kafka_2:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, INTERNAL_SECURE:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SECURE
      KAFKA_OPTS: " -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server.jaas "
      ZOOKEEPER_SET_ACL: "false"
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.auth.SimpleAclAuthorizer"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: "User:admin"
    ports:
      - 9092
      - 9094

  app_3:
    image: cp-kafka-test:6.2.0
    image: cp-kafka-test:6.2.0
    build:
      context: ./kafka
      dockerfile: Dockerfile
    hostname: kafka_3
    links:
      - zookeeper_1
      - zookeeper_2
      - zookeeper_3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_3:9092,INTERNAL_SECURE://kafka_3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, INTERNAL_SECURE:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SECURE
      KAFKA_OPTS: " -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server.jaas "
      ZOOKEEPER_SET_ACL: "false"
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.auth.SimpleAclAuthorizer"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: "User:admin"
    ports:
      - 9092
      - 9094

  zookeeper_1:
    image: testzoo
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    hostname: zookeeper_1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zookeeper_1:2888:3888;zookeeper_2:2888:3888;zookeeper_3:2888:3888"
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - 2181
      - 2888
      - 3888

  zookeeper_2:
    image: testzoo
    hostname: zookeeper_2
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zookeeper_1:2888:3888;zookeeper_2:2888:3888;zookeeper_3:2888:3888"
      ZOOKEEPER_SERVER_ID: 2
    ports:
      - 2181
      - 2888
      - 3888
  zookeeper_3:
    image: testzoo
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    hostname: zookeeper_3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zookeeper_1:2888:3888;zookeeper_2:2888:3888;zookeeper_3:2888:3888"
      ZOOKEEPER_SERVER_ID: 3
    ports:
      - 2181
      - 2888
      - 3888
